### ISSUE TITLE
8_queens.py

### ISSUE THREAD

**Issue by RavenHex1296** [JHpusd/machine-learning#2]
In your same_diagonal code. Instead of doing 
delta_y = point_2[1] - point_1[1]
 delta_x = point_2[0] - point_1[0]
if delta_y/delta_x == 1 or delta_y/delta_x == -1:
      return True
it would be more efficient to just write a slope variable which equals (point_2[1] - point_1[1])/(point_2[0] - point_1[0]) and just do if slope == 1 or -1. It'll save you a line and is easier to read

**Comment by jyhong05** [comment]
Changed that, thanks.
