### ISSUE TITLE
linear_regressor.py

### ISSUE THREAD

**Issue by RavenHex1296** [JHpusd/machine-learning#3]
I noticed that there were a few times you could of put an else instead of elif statement in you linear_regressor class.  Most notably, at the end of calculate_coefficients() with you elif i!= 0 and at the end of predict() with the elif key not in input_dict. Although it wouldn't change much it would make the code a tad bit easier to read and comprehend.

**Comment by jyhong05** [comment]
Shortened it up. Thanks.
