### ISSUE TITLE
Code shortening, and minor renaming

### ISSUE THREAD

**Issue by snowthesprite** [JHpusd/machine-learning#6]
While everything works fine, there are some minor things that could be changed. So, starting with the renaming. You should probably rename the `d_column` variable. I can't really tell what it is, but I think its the y variables. You should rename that for ease of reading later, both for yourself and others. Second is when your forming your `sys_eq_matrix`, you can reformat that a little to loose the first if statement and the elif statement. Set it so that when you append the empty list, it has a 1 in it so you lose that `if j == 0`, then you can just straight up get rid of the elif statement. The `continue` will end that iteration and start the next one, but since that section is at the end you don't need it. This makes is so that rather than your code looking like this:

    for i in range(len(df_array)):
            sys_eq_matrix.append([])
            for j in range(len(df_array[0])):
                if j == 0:
                    sys_eq_matrix[i].append(1)
                if j != d_index:
                    sys_eq_matrix[i].append(df_array[i][j])
                elif j == d_index:
                    continue

It looks like this :

    for i in range(len(df_array)):
            sys_eq_matrix.append([1])
            for j in range(len(df_array[0])):
                if j != d_index:
                    sys_eq_matrix[i].append(df_array[i][j])

And that should work just the same.

The last shortening is with your coefficent dict, where you can get rid of the if and elif statements all together. When you create `coeff_dict` make it so that 'constant' is equal to `coeff_matrix.elements[0][0]`. Then you can set the range to start at 1 and get rid of the elif. This is so that your code doesn't look like this: (I took out the `no_dv_columns` because thats not being changed)

       coeff_dict = {}
        for i in range(len(no_dv_columns) + 1):
            if i == 0:
                coeff_dict['constant'] = coeff_matrix.elements[i][0]
            elif i != 0:
                coeff_dict[no_dv_columns[i-1]] = coeff_matrix.elements[i][0]
        return coeff_dict

But this:

       coeff_dict = {'constant' : coeff_matrix.elements[0][0]}
        for i in range(1, len(no_dv_columns) + 1):
                coeff_dict[no_dv_columns[i-1]] = coeff_matrix.elements[i][0]
        return coeff_dict

And that should also work the same way.

**Comment by jyhong05** [comment]
Thanks, I fixed those up
